name: joey_loading
description: A simple Loading package, supporting iOS, Android. For asynchronous scenarios such as network loading.
version: 1.0.0
author: Joey <332006721@qq.com>
homepage: https://github.com/joeyczz/flutter_joey_loading

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: "^4.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
